version: 2.1
orbs:
  node: circleci/node@4.5.0
jobs:
  build-and-deploy:
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: 14.15.1
          npm-version: 6.14.8
      - run:
          name: Build an environment file
          command: |
            chmod 777 ./buildEnv.sh
            echo 'export AWS_ACCESS_ID=${AWS_ACCESS_ID}' >> $BASH_ENV
            echo 'export AWS_SECRET_KEY=${AWS_SECRET_KEY}' >> $BASH_ENV
            echo 'export JOTFORM_API_KEY=${JOTFORM_API_KEY}' >> $BASH_ENV
            npm run buildEnv
      - run:
          name: Install aws cli
          command: |
            sudo apt-get update
            sudo apt-get install awscli
            aws --version
      - node/install-packages:
            cache-path: ~/project/node_modules
            override-ci-command: npm install
      - run:
          name: Deploy to s3 bucket
          command: |
            chmod 755 ./deploy/deploy.sh
            npm run deploy
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
